// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPG-5SqeZ7_kbqTnXdZriiX96agHbYHgE',
    appId: '1:209078072944:web:4a91b6471ccf5dcf0e26b5',
    messagingSenderId: '209078072944',
    projectId: 'k-star-app',
    authDomain: 'k-star-app.firebaseapp.com',
    storageBucket: 'k-star-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCeRmn_l8f2ivxwCMUpkprlObifTUpqPg',
    appId: '1:209078072944:android:4cb37799db3162120e26b5',
    messagingSenderId: '209078072944',
    projectId: 'k-star-app',
    storageBucket: 'k-star-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPG-5SqeZ7_kbqTnXdZriiX96agHbYHgE',
    appId: '1:209078072944:web:ae695a78397c5e940e26b5',
    messagingSenderId: '209078072944',
    projectId: 'k-star-app',
    authDomain: 'k-star-app.firebaseapp.com',
    storageBucket: 'k-star-app.firebasestorage.app',
  );
}
